---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nvidia-device-plugin
  values:
    runtimeClassName: nvidia
    failOnInitError: false
    nodeSelector:
      topology.kubernetes.io/gpus: nvidia
    tolerations:
      - key: llm-workload
        operator: Exists
        effect: NoSchedule
