# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-db-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:QMrYkb4=,iv:cC2QLfzLfuMjj1ljZkm3ZG49kahtgCaDBgG8hHjXOVg=,tag:6QorGUIckKi0zoS+k6U0Cg==,type:str]
  password: ENC[AES256_GCM,data:nD9CInVCArT0DTDY9aVCs4XDyA==,iv:Dd0HkcbsEcVxlnGFBtQLwmHXyA2rIT4+YhdmHC/LTV8=,tag:gHxSYu8WnJpsdzRnau9ibg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdHA0eHBwNnVZTWUvc2dQ
        anBXMW5rUEhlNUZ3M2RuT2FWK1dPVUJFRUd3CmtvTmhmeWJFdGRoS2EzZG1QQzZS
        eHNQNlZXQ0JydVVQd2V3N1lqeStNT00KLS0tIFRWaFRxcjhROTc0NE9FdVNaSW1W
        aWZsSWZsUWo2bnhHTUp6alo4U282bVUKLgpZQd51CrSaOt6CVC5gb+94mxQ7hDof
        J9MUUVe2QH8/29vFYcdC7o4pqlbdj4RCS+0SogAQoXafu0Hudyxq/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T05:31:38Z"
  mac: ENC[AES256_GCM,data:qpHHPhPxvZFK3N+DCCZFRDsjR75m3EPxUJxSPw5IBvT+aVTfrYLdXLrqa6dRcTXDaavJJI/fRUABiwzef3D6IaS5/rnDd9zdfqs2UKgsmY/WdbsK3Dcw36sYLFya5cfdE8B44YHyQ4NXQAUON1lAg8BjxAJVuoCIr13c3AG1w/M=,iv:RAeOHzUwmurZQpma42S5goVBUjsxsNYxw6gOws+RnxQ=,tag:utnv7jDB7+9aRM8ZQztsLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
