# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-db-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:SvjRVjU=,iv:W9v1uXX0DCj2OUorXTV/XsDLa1i1JKll6gsesFiH4vI=,tag:X1iPD1a1S1XOta4nIuiygA==,type:str]
  password: ENC[AES256_GCM,data:nC2BwDx2CPUY8avumaBz2kGRkA==,iv:fbiWaxUxe8CiLKRT6XF+Egqz36ena18foCrAxZDo6Lw=,tag:wsGeDIf0T6eGgKRaOnWDEA==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M0hJUDQyaWorRmFWQmtJ
        VzA1RGlZZlZLd0RaMWt3czU3YnFaZWliVEZZCk1aK3FwVXltaFFTRGFZdTdhVEEz
        UmpuWE1ieHB2dU80V0hoOHZsNy9TdTAKLS0tIGQyRWF3dmJhV3p5OTdBMEt6WHhB
        K0JMdlVybTNEc1dDa29GbVhMYS9MNG8KmUG67Kn9pflTv2R0lnqzRe70ZRMw38zC
        NlDy64pA+l5kL3W//eNc/W/Tg0A9w3JnHfc7D8zsdkbf5V+LE5Oj7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T05:45:53Z"
  mac: ENC[AES256_GCM,data:63HCF/yBSq7vv1qvh+XkBD2Jc0QZPErz2HLwiNpcJF8aka5GHXGvcVJTFCJrFhjFVvQ45MSaPdiHt3/OQ2jXMODpkmH07gAuVdDEkrlnCeqtMVXnA0V08+5DDVBc36ezRd9iCB6N5F4Ctz6BwSClhsoAgxyYi9LYIpT/mSizrow=,iv:PRFenbqCMBGiwePOzW43BzoED/JkFy4LUOW3S9OzzCI=,tag:xSZ0MKR2UtLTchxFnQYgKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
