# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-db-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:nkzw+6CYW8dtZmkymKzOPbg=,iv:jq4mIB8TIEs9XA8lIJVzmwJLv4vzDqqm42Iqr8XBkQs=,tag:emzcGw8cvJ351HpDlPALjA==,type:str]
  password: ENC[AES256_GCM,data:ZIBJsT8wY1a8+qZlh/n+5dP3Dw==,iv:8UjjDZMForNiIfBlaY3YZdTF2fj/HIUKgbR+bfXXYkE=,tag:iXdrO1NcsuDUB8wdjvIJxQ==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb3BkdzlnNGlrRGZBVkxt
        MzlSYm5MTk5CR0NlWGxvSFNWRmN4encweFJBClhBak12QjZ4QjkxVlNNYU1OeUp3
        RkVyOGU4T2lZV1pSOGZkU0RVaHV3dlkKLS0tIGZXT2grT1BPQm8rVFpyREZYUG5Y
        YUV2ZXBSUU1NQk81WVpWZHN2VG1XcXcKsLQPeU+w1Xxp51gDMtGArgO1y6oQggAM
        /l3Oy/Oby5IqOdUUNt69/Fj6B4HDIkzbsQALAbM7QsHzrPgVT5aBcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T04:21:06Z"
  mac: ENC[AES256_GCM,data:OfY/PbAt6bhnhpbkfnuKs+WXMOxZQjG77Pkdi4KoSBnK5apHjij1pjwr1uxhAqFrMOFeqc2p+pTYMufWIhCvT/G2NSp2Bk8XY02bytXsbUG+eLw51zoAIdcjbz+4hzdjyC+7vtqnF+SPYK1f9X8Xl0cg7QjztMmr96YrX4ifeRA=,iv:wRoDCCLPnOpH3dHlQfqev05hOSB5egbbdYRkWLjPkKg=,tag:eK38siJ4p7XXxGEkWJ3Gvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
