---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-secret
    template:
      data:
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://miniflux:{{ .DATABASE_PASSWORD }}@postgres17-rw.database.svc.cluster.local:5432/miniflux"
  dataFrom:
    - extract:
        key: miniflux
