---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/rook/ceph
    csi:
      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 256Mi
      # NOTE: Enable the driver and shapshotter if you want to use CephFS
      # enableCephfsDriver: false
      # enableCephfsSnapshotter: false
      enableVolumeGroupSnapshot: false # TODO: enable this when v1beta1 CRDs are available
      enableLiveness: true
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true
    pspEnable: false
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}