# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:rNdKSmHiI0+o5CDOQz0WYfEgQ15QqHCJN9pPY1hBmbecNQMV/LAsQGlDZfjbBCzL6i8NFQpTzK4oqStVnO452I+48MqRlhQH0soG9W1dsoDPOQwXIrb03S99os7edAhyeHCzre1OKaPsFBS5zX7ChbrZIdN5C4fsDg==,iv:x7sFlqA70/cUxHIVZMcUUgUrqyKjvI6ooPjWE3ocIc0=,tag:ZpQpdYZAXGhILLLWOwoV3A==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZUZ3M1NrazdwaTBDS0Qw
        SXlReFBFK2l0NVp0VnNwN2ppcHZNS3hwMW1NCjhTbTRWUzdzUEpGWTRPSnVWSmJj
        WHVYM1ZGais5MTgydzVQLzFPbC80aW8KLS0tIGJvTVhIeCtPZXptclBubUtVWVg2
        MGVkczd5ZzN1UzB5TWdkOGNxejlpelkKd5q0pFPwG9rTxGA4sBfQbd8UIxil/M1b
        RbKs5fl7K2og9gaoGvkuCSuOMxIFvC9EvdUztlFhlVdRWke6q3wFpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T02:03:00Z"
  mac: ENC[AES256_GCM,data:cwODXnPraJWJRPxyxSFaCeVnomwwwF6tP27s/0RkRZJbc9vpmAFUWZ0a+qRyYHQCnq7kU6ayuwHcmse/Q7+f0zafbVYAGOcDfnQOu7EIUT+ixLoMsA1zZzuMvUZlry5mkVlyM5Imtqhu/JFNXQw25Rms4Tw5wI8mcmMisTzq7U4=,iv:i73es6ZvWXwuoLvwWCCYyzLs4asloy5nhYk91itqPxk=,tag:7aQK+cQ0j7JlsiyQOXrung==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
