# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:NAf1fkRuIvmg5GSO129MxvqaDx8museNYX5SAHZWpdaLr834d4xmD4D4dHvjDDQS0V8gyqFuZbTXOgMJ4yyMf2jHwCn4aGgr2UwaV5vaQmzb/ZGYNhaobYtBLcJXxNBkf8higmq638kePMgiFEFFUXSjsVKiJjXtGA==,iv:/cWN96VLE7GNDZTS0ote/WqrrFAWMVHD1+3VfsZV3t4=,tag:45vYBdutrttZGHWD/FoZkw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYUdwSEhsdEpjNXR4M01K
        TWk5OW5mdjhlamtwcC9EMVRWc0ZvNW5rSG5vCkxuRlB1RW1wMFpGOWZ6VTlNWm92
        cGhIV213YzFCN3JaQm50YnRvVm5lQWcKLS0tIDkrZXBXdStZLyszWXNRZjBpMjY0
        LzZMSGtpR2s5dWx2TnB5Mk82U1Fod2cKvnXQj/5bN0vb2ZKmVJ7CjGi3ABL6HcLT
        n9D4ssAiye48ANg3dCNzICZNkL2Bl+gE3ojLr/NiShfaf5/SmZpq1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T01:53:46Z"
  mac: ENC[AES256_GCM,data:QqU3+qpBAukH+A8uBBQmJel8N04RjETRcyH4tGzfVfuosDY8i6oabpYHG0kTH10qWh0+NgsF4bfstnTZZyKYxjCixt4427Qz1QcDD9DqyR09cC3QE4q+Yrug1oPcrczKG+nuHt0Guwjuf65nS4PQ/7tBDsG1synDnfDSk2Q4Mbs=,iv:FH/vZd9zJOKIWuTp41ofZ956I5G24rjgMy7icm18ynw=,tag:JLV89EvS2qi8VnCR+NlcpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
