---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: dcgm-exporter-metrics
    files:
      - default-counters.csv=./resources/default-counters.csv
  - name: ai-node-dashboard
    files:
      - ai-node.json=./resources/ai-node.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
