---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: upload-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: upload-assistant
  interval: 1h
  values:
    controllers:
      upload-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/audionut/upload-assistant
              tag: 31.0.2@sha256:6ecbdd9287e1cab58bccd1719664382ee7ef7356df4d47429e426b5d365b45f8
            args:
              - --webui
              - 0.0.0.0:80
            env:
              UA_BROWSE_ROOTS: /data/torrents,/Upload-Assistant/tmp
              SESSION_SECRET_FILE: /Upload-Assistant/data/session_secret
              IN_DOCKER: 1
              PUID: 1000
              PGID: 1000
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              # capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dovis.me"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      media:
        type: nfs
        server: lil-nas.dovis.me
        path: /mnt/seagate-data
        globalMounts:
          - path: /data/torrents
            subPath: torrents
      config:
        type: secret
        name: upload-assistant
        globalMounts:
          - path: /Upload-Assistant/data/config.py
            subPath: config.py
            readOnly: true
          - path: /Upload-Assistant/data/session_secret
            subPath: session-secret
            readOnly: true
          - path: /Upload-Assistant/data/webui_auth.json
            subPath: webui_auth.json
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /Upload-Assistant/tmp
            subPath: tmp
          - path: /root/.config
            subPath: config
          - path: /Upload-Assistant/data/sessions
            subPath: sessions
