---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: twingate-secret
    template:
      data:
        TWINGATE_ACCESS_TOKEN: "{{ .TWINGATE_ACCESS_TOKEN }}"
        TWINGATE_REFRESH_TOKEN: "{{ .TWINGATE_REFRESH_TOKEN }}"
  dataFrom:
    - extract:
        key: twingate