---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
spec:
  interval: 1h
  chart:
    spec:
      chart: connector
      version: 0.1.35
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/twingate/connector
      tag: 1.90.0@sha256:833e7a968f1b3a5ad79b88b04f82aad1bfc8621f61b6b35f01be2411d35beba9
      pullPolicy: IfNotPresent
    connector:
      logLevel: "info"
      network: "goatsinapond"
      url: "twingate.com"
      existingSecret: twingate-secret
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: twingate-backup
