# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: twingate-secret
  namespace: network
stringData:
  TWINGATE_NETWORK: ENC[AES256_GCM,data:WP+vMWczM3lIqvRz,iv:ZiVT1XO9lbhNDAjLWNN1Yyy+I1rmbYsk/miaHG9ddpU=,tag:W78Rus3oOaEweWzuiAAd5A==,type:str]
  TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:Y3PEkruyHB4P0wb5SAb54o/bdp2V/NHfKeU6+8neqMU2LqQfkrUfjRMTfX0nqO3Pu6oLlFCbJGxHbTfQo93kUL8CkL/KDzOT+nKzcyZJVIllnwCfDV7yXDpSGXep61M9gneFt0ASVEkcwfSY3UttyKD3uw2gbpJBirfs11Yx1qq387m0twq0lUowxgknu49RCclKjWt2oGnvrtDPooKGSgijf+v6qt8FLeNzgbtq6f213vmP1nYQWt2qtwGUbL8cdwnixd7//3zqnUTQufYsFsfAR39fWnF7qs+9tybv8rfsCTw/AO5LtbR4oeB2qSR6tqqk0ZgbpSOEMH2yvHOa2cSUG/Z8LllIawRhu45uBnhXV9JiLI44bPi4GD1ohjj3VfKkCLcF3zlokE2S3vVFaN6U6i4Ky2foxrz3PHeTwV8rELLMUoUTfZqz9yPx1qxC2Sma0GH2oFFavHwjuVEmxDrvEBjziMGra48yEJ+jZ41Nb/gyqaVaOT63wCqC+aCIvnj8LIZm0mZ+uM0P3ErYW+XokAqtp/f1iVFgGeHbQVh4souJfGiumMWGl8+8pQgIjWrXSxBLJNkeQCryU6mUWI05/Y+Ggpxk7IBeN45wlTlVHp063PV4qb//zUojd9EuFiBp6pqn3251rzvEZ6hy1bU3VzGnpg==,iv:feHOipDYck6RQ93hTI7zhAFhsDe2HJtDdCXOYMxnLRM=,tag:n1IT9DKIYlSaF3yM4VeeHg==,type:str]
  TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:W5pphKH3Wiq3As28KIuSthspsaWBG2BJs5HFlDdHkqTy5WrWsOZASCOWF/F9E+TXK4fFpNX9Z3BN5oxQb+3ANi0Ma8qXrBpUvARxVMx4Q0Q4V+hZkH+jNxdowoezgf722NeeKZLxvNB89PXw+4NL/II9Igbr8lOsib40f2V4yWPb8INfLm0=,iv:EFPHu9RnnU9p+g9A2XLiqo5HyN9LmpI9NNQk+qe61VE=,tag:x3LyCzwYl12MiYPNFDMxDg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL2NXTDJWaE4wSW45NHdL
        SEFEODNOZWY2Z1BTNFVZdDNKL1J5WXEyYXprCkhZZUI0ZUtoSFRuR2JWY2NWbEls
        OWNLVnZuajZTZGZSYzlkSDZXTmlvRmsKLS0tIFZnbTFnQWFzc0hnM1c0Z1k4SjE3
        Q1NDdzlLS1pIVTdLNUhQaUdoNGFBL1kKTFBWNbzyoxPNpS/r3OZ7VYhNtWVQmXq4
        O+PJhqhLa7RnEYICzYJk8fEDeRJPl9lrIKGigiAPgUn+meuhxncD6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-31T16:47:31Z"
  mac: ENC[AES256_GCM,data:pnA7F2NaUferRcm05Hpl+EyulpKTdAByXbFTIaRN8+cv04x8iygAHH5dYd8M6krYMjkwE+If15DPv9kpF7h5BEKDECkmR0iMyA9cZTQ2cUwv/Ij1H0QdpCjIVlMFqvFvLk4SMKW8IDrITp6WB/h3Q5U0ZJSVjZcvW7tLTqMRJOg=,iv:PHLheHHRKTxnL5ZrwTMRzhs9vmg4S6c1r2oDnlSK1TA=,tag:djSydXDtMwU6cEi54QHhjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
