# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:KjDWHdiYWvQBcP9eHPM1fW+TpHceUM7YGFxcifLA37A=,iv:0U07nHpBezL7WnPZWWPvXkfJbfsqL4hhD3KtBNM5ldM=,tag:2+eFU3ahK5TFv6WOd/QJVg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZk9TMEJVdTluS3hubmV5
        eHJtTG9zQ3MxY2trVEorbFovM0lJQ2tmMmhzCloxYXF1QmJVT0dvdGlSVjdZZ2JQ
        YU1VbGJyZ0lnSG8xTWdMbGZlNzZ1bG8KLS0tIFZkYUZHNVdiS21wcXQxQ2lDbGhC
        SkVnS0FxMDBYcVFLSnMxRTVPK054MkkKa+RfeusMxvW3ToPPb19sbIm5fnIozXwG
        xcxLrbYmJr1dbjsBJVrZlVc99iHKzyb/op6hN+hj0UMDTxndscBxKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T20:50:22Z"
  mac: ENC[AES256_GCM,data:HMOoTSq0/gfxdskmnIzPBghQ0RLj3RsNeyok5eDIIrlkyGU9JTR9eIORrOxIAG0ST+uzPixeaPgUZNzqnSsxlcq9efjMtnVskiFgiQBC08kif3h0E7bre2+c1s4960q+Toz8l6lGMVOC5sHNz/M6zpTZIDjgTTXbwQEy6IrffoU=,iv:lP8x9pryn/rTtmzIIH7/7kP8H3V6scimHXAHd61vno0=,tag:HwP5EbkXPSEHDf/DktIFzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
