# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:vA9eHDc5udC3OmVfA+twwPkRReFUs0kcL22tp4QLqnQ1D5QwFxvl1MHIIMLVLQ9xvAr7mmW88oPAnfWVXxXQoQ==,iv:133w4p28arnFsfJ7f0YCJNeJEJEE5nX2dSOJ3xs99yo=,tag:rXQmNheh+IzcvlW2oHQJCQ==,type:str]
  PGHOST: ENC[AES256_GCM,data:0VlM7MMVF7kK/9/ycKaULTrbfDuMdb0sufLltzgvyZ1FWApK5upG2g==,iv:QQre0eVZZN+y40mger0X3fee2cH+L2TiEeMg0EmcRCY=,tag:bsed75DNFgnqL7kF3Zlvvg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:FFhziA==,iv:vUypTfEGCYvL4uji5ZsL+m5DK0T6LhSJaQPO9pSIp2o=,tag:uAsXDbLi/ovHqdL9cnEr/g==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:sBYWihs=,iv:zyHfcQjpXVv0YMV4q/bHNuVM0cZCPHfalQwhx8h+G+k=,tag:kOPnI3zTjvs+P+8/1EzrtA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:H3DD1ftYrEBbV4dsAgMDeOXRGg==,iv:LiNA85IEb4Vfbr92nhFKlDtmCrgr4QXS53XXvfwQx/A=,tag:m3YGtBjiICFqBunaGjrNBg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:OTtId5o=,iv:U0nsJwPHfacAz+P+Lq/ScDQCX/9e9eBAhqoqbZW6gQQ=,tag:fjSsf/60DXoGo6o3zciqrQ==,type:str]
  RABBITMQ_HOST: ENC[AES256_GCM,data:E1LhodA//uvcOYzf3QKJPQJ3iVh0EG2RmGL4wDCHndpRrn9Y5rE=,iv:UQQtGENb/Q59LsxHnnRbBHPvfEoRER30KKPQUAbin8A=,tag:r4EFbvCTUHi5/HGhWPT9ug==,type:str]
  RABBITMQ_PORT: ENC[AES256_GCM,data:X7ArIg==,iv:Zyxi9J6U0c4BN41kYMVaC7QPfpNVSTEsfsZU2qLgQTA=,tag:eG4ffUPgm6cj034RYuyiqw==,type:str]
  RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:qVf5CTQp/IdZjP5XJb4=,iv:tlbP566y3tpSYc8BVwmPLkMdknveb0xlbcMKawKGj7s=,tag:7He6WagWUSQGuMg1o5ykDw==,type:str]
  RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:h/9J4ZjH2aQykyQxkwgj4xkYOw==,iv:hq9tD6Pv/+DAf6nBv6SvcoiKm126T0frgIgA0m3VpwE=,tag:rH2qX/aX1folPDVf7pKc8g==,type:str]
  RABBITMQ_USER: ENC[AES256_GCM,data:6pF4riDde5R3Eqf+URQ=,iv:1cUTU9Mj1reqlNqRiHpmDCb2ldNRiaIWsoIdZDZKZmY=,tag:/aJphE9cwMWSYMXTzFVPsg==,type:str]
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:2rcbUn0tpdogTgxHLkluMBSGDg==,iv:dXBgKY3G1CbWPQUIOYHH/FWRDnWpKCr2qebdG+oQYpI=,tag:Y6pq1yFLVGzjffRM0PiR8Q==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:GrKEmP8w6l9CuXWgnVghKjfoqUtAV/fpIpG3miZkEkza+LLUhnJyhPjpfMlUARI+,iv:YGkAoAGIITIZggSviIUVk3WEoaC6twm2c0yQ/MIP5sc=,tag:d/wisASZgIys6mEHgGIIAA==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Nnk4SzMxUzNzYnAwQ1VM
        NTcxYjJYWDZKcDUySzJxbndvcjZ0aHpha1ZVCnRKdlgvaWtHT2RDQkRwN0JxMDM5
        aHE0L2M2TXQxN0h6Zjc5Y1BnRlZiajgKLS0tIGJqbGNMVm5SZEkzZkRXTFRVRFNH
        bzV1ejNOQWwzSnNybU9VM0c4eEVxV0UKvGSDrdn2IYDHUIPOfRKHECBRXq5uNugN
        henFzG3qyIU7uKkyRIORAeUh3ECJbpileZMT+hMKF1MCAqc4JDd9oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T06:35:14Z"
  mac: ENC[AES256_GCM,data:q5ukr5cDXBFPrdftJsJugCx81VkAF+TalwsQBibTfoOHYtdfKgiKMVGJRoKOL/o6Sx2huhHTHfM1b+XpbDFL/Fza0Bb5vYPXdgX4wRFTKMHnzXSSYULWrCm0s4sfzS5fGSlsfSCpYrC6zpG7Wm+EoztP6oZXJxEvlJRw5P2z42Q=,iv:C2D1csK+P6Efm6FYxlfbD/MJ3ch7N2GwrigIJ20Qnsg=,tag:ZcRA0Xn0vYkdKzjYg8N0RA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
