# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:D4tFpTgkzLpgq2IwZ5MbONAVte1j0Mb9L/sI9cT9R5dmNRBaiZyPmtLXsDE+0G2QHOlDlFFNBFVQQqavMNh4LQ==,iv:SX/mXo6BnLN5L0wwXQdkZDdvc8ZmKV6156g0EuJ9bD0=,tag:0+eTen3xwyFVUprb6bxv0g==,type:str]
  PGHOST: ENC[AES256_GCM,data:Oy+DDrxte+OAtAZrOT7Z4/U94g9Kijo6AVLgjQWb0BvOmwf6Td3VLA==,iv:C8rMuUA71ARf7NLkdbe5lWSSlUxiW+rRHkWWWcp+e/k=,tag:z2iIabbWlOVMyTzdYlKj4g==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:VibKLQ==,iv:q/LKeHqCyH7nVszOHkeNNn0OgCFHYuR+MmBluVTHy+Y=,tag:iuVo1osqkp8LzWnMRP209Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:1A35bDA=,iv:GPLr14KC1f/UgSeLC4L20zRgoWwMAXpHOkwf84EctuU=,tag:PxIjyZRBU7Nt6UiQnh5P7Q==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:wx/h1oribapAvO6ISjfI0YN18Q==,iv:4A2eMJaK2bKk9Xz9ox6SgFs9H9jyNKaFG4vXaeJI27Q=,tag:7yq+W5yM2j2bZhXWLuvwQA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:Ne2OWVk=,iv:O4LjoLg+py4Rwa2DOHLzYgItQXL2yyAFUXTGUsM0Lb4=,tag:IR8DLfPjdLy4FiRtMZGwNw==,type:str]
  RABBITMQ_HOST: ENC[AES256_GCM,data:hW37pyP9NmUVtUv3zR+bdhdLaWTpWYOoEqdD8mszDHnaRFrIJU4=,iv:CmP4OX3ttMXeriQ25qBijA6qrxSGhDldcifyHola2PA=,tag:M5Vyv9+nGSjTmdMAt+dV/A==,type:str]
  RABBITMQ_PORT: ENC[AES256_GCM,data:0gzWzg==,iv:rywspNSGoQgILHs9QGmCdKroach1JA6OT05C5ZmfBIE=,tag:WpiFzTwgvXlxxu+TDRmEMw==,type:str]
  RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:lmu4lsj3aAMBaaWnO7k=,iv:NrNDaDiEURQFw0NMWA2S1x2Sse7onorcUf3URSCiyFA=,tag:TSfIUuZtZnjKl23Yd1Zm0g==,type:str]
  RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:xepfEBoZmPNQnRBaSirmdpysLA==,iv:nRuWoVa3aR4B1LcQe+0E95f3GMtZ5KVfEAw0U8tUML4=,tag:wFphCixJ4xuO1aEaPX5GBw==,type:str]
  RABBITMQ_USER: ENC[AES256_GCM,data:XxNOT3iGdExXSrA131o=,iv:u+Xoq6K1G0kP5D4sww93+RuTpna1fsGYzoCuMWWP7QA=,tag:FbIz8LVayBxLobhy93muMA==,type:str]
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:tCA2EMPZMLzFDzWalR0OL8+62w==,iv:Uw2vhWPKk7aO28zEe6eFFmSx9xiMqy/jX2JE1ZlWJ70=,tag:zj7HICyUU4WuiabpQAc9mg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTmFIUDh4V0pvT3g0dWxU
        YzRPYTk1TGllSVVaOU9aSWVudUt3WkpxMUZRCjdLWkZlYUZLOWQwQU04RUsxQ0hJ
        STY5Qk5lKy9YclR3M3dmdVBhdFI2WUEKLS0tIHVHTzg0VC9zM2ZmcU9kZ1R6UXk5
        L1gvczVEemViUWZSbDN0b3F0MnJkOFEKgyzlvW+UjbIGu3CHbP0isg+Ezpnh1cbO
        6MK2QotRWx+haTkWJEzyzzQ1VIzWLffhBEQmlgLXgEVdQo8imQcUJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T05:29:53Z"
  mac: ENC[AES256_GCM,data:XQ+59ScBzxchmTqM2r9c1LiSx5jeFC3A4mddePxFZyBs6WBFeSkJ5PSXqH4OEddj2elBM2zZPfnIPC5EXYsNCEmViv5hGGV7uu6H8DkzsyfAoH5/oMREAFicHMsWviau9R9hqvhxeCAq50aUrtYiKJ5hJNQ5nYyoemIBalelWcg=,iv:i5wG5OG5cVBS6BQo/IYJ25OUY9TLtUv8NWkCNuPlGdU=,tag:asIJpPpMxjzN03+1TE5Txw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
