# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plane-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:zFQ1p0Be/O3rcPuWGTfjXwUJQ+Rpsiu8WvoVNB4NbMemtiB0MFc0FqAHEsH/6dwA6UKz7LL27ZcAb4KgdHDbjg==,iv:L3KV7JnRB9gGRU/tcbymkD8dNpijjMGrVXv6blAe23o=,tag:Ecm7GAhvzvHXl0s7t5MEgA==,type:str]
  PGHOST: ENC[AES256_GCM,data:5VkVpHmK2RuAvPvbwF919wb3O4vCjFE2iHcKIznIoP5mAzpyB6ipjw==,iv:44odCwVeV32yW47sGxqD8dgh+P0EO052V1Rl8cijx8M=,tag:qIVGGU7HFhQ++XxAxfKX/Q==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:V6hHrg==,iv:OBNOMvsJjRs2hR1YH863drdetQb2bTo44RkqSgzdWro=,tag:126w1ZhXTSmhZdUj++tynw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:nhu1DJc=,iv:1DCZa2drwUhZIaa0d3T+CGmMM1Q7RFKYjwTQ6vw9Tjk=,tag:x/7X0cH6qaKtwVlLvwRpSg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:BxOu4Q6W5JZVcku0lh+lP8Ztgg==,iv:S37q8/sVR/bIdcACMquZvwXJRLtO9ylbkWQjDCnzx5E=,tag:Bw1LLYH3WU7FMHpfTDIdnw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:007xcP8=,iv:8PsUx9hYtweW7GYfUvzpgK9OnVdwOPebekZIIRs2NV0=,tag:oC6QrzJSpSB/+h0eWUWG2g==,type:str]
  RABBITMQ_HOST: ENC[AES256_GCM,data:Rn1A3QAz0xX9MZn4ZFTqwpWLskGPWrQXtDvPsTIhHzfr1F1Ffkk=,iv:kVPMrLzSGPCU6RcmHRsov3iLjF5US0UdTLdvrPSLEew=,tag:EKnJtRmcRu23tt0J9CK5QQ==,type:str]
  RABBITMQ_PORT: ENC[AES256_GCM,data:XljJyg==,iv:RFoUy1d2/5SXlIM4bHa0JB5fzpNaatItD0ybEm23XvE=,tag:mDzCgtyo3MnX1CLnRxOXhw==,type:str]
  RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:BXVDfjDTYQvncgWJBxU=,iv:dKum2g4sxJKQOWqnNNvS9+36B1Y6stMO8dLjNp4W3E0=,tag:4Vnw7hNs47DffBv3Rsvdbg==,type:str]
  RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:/2OAVpCUdp9+VtYixeEV6j4gaA==,iv:8N4Ok83MPllHl/tTxgYFuPl2GxhP9iV869050vCO2nU=,tag:x8CVR+CWGPUZZp7aP9mxVA==,type:str]
  RABBITMQ_USER: ENC[AES256_GCM,data:lVK457w/4asFSAPc5CE=,iv:iQspahrcRTrMb+0KjRqJZIhyfbxta5qvta0nwxnRWEM=,tag:pbkBrY2I6iaur2uVAkKGnQ==,type:str]
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:yi8wstZTlqeb0JNwL8enOWZwvQ==,iv:5dYlnoiLfIcbn3SriRp1xeKSHR2l5dQjTeAzcdcB6gk=,tag:Sfczb9waEg1TFuzTl6EiqA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:7lLOJkWAhYtBVlxRfmCYBNdlTW1SLaNTb4tqBfD3UOf9kJPXmSqsf6GRdziJMWp7,iv:B/+3NcdHNLn5+gWOdYEQfMqspFVQIdbyoSQnL4tJmis=,tag:Gyybhn0gIlNnf0KWCof2zg==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK1lHOGtPb2RLcms0WWNl
        RlVpcGZtZ0pEY1lDOHhkMm11U3RDWUx4dUdnClJzdzVCM0dlek05c0JqQzJGYkJh
        Y3N0eUU2ZFFrWFA0QUNhLzM0dHJZTVEKLS0tIGtFaDY2dG5NUVY3NHBLZVJmcWN1
        RG5rdkUxd0lpRVY2MTBHUUt2VFptZFUK8+ImNAEgYsKmTHyIowYvfQ5nAW6MYeO4
        oqvylPiRIlBOKve3r6/naa33H930YFC4bIO/OvmaLKk3tt9kNCODmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T05:46:49Z"
  mac: ENC[AES256_GCM,data:9IvsASI+Mi67qBsZ4bxJlN17ECg7ohjkDf5cHzGTQgnSvAUpqwCR/O/NqTtj+X/xaE3GrMZc2qJk1oXXsAqSwer6+KFugSVNXqdNlOEjelHhHAXXeOF45IKyytzyWpLS72JM+sjhuU3U24xrwqSgIIEiB/HPxOkFSVs8PA9SaRE=,iv:ndYHmmp1NnK/Nj8yf+4L4u+E4mHfKoLObfA6QK3XGho=,tag:SARaOUTAopd/xBAZwYoTfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
