---
originRequest:
  originServerName: "external.dovis.me"

ingress:
  - hostname: "dovis.me"
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: "*.dovis.me"
    service: *svc
  - service: http_status:404
