---
endpoints:
  - name: "${APP}"
    group: guarded
    url: dns://1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.dovis.me"
      query-type: A
    conditions:
      - len([BODY]) == 0