---
endpoints:
  - name: "${APP}"
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.dovis.me"
      query-type: A
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
      # - len([BODY]) == 0 #onedr0p how did you get grafana to work with this condition?