# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnativ-pg-secret
stringData:
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:6pLWv6+hipdy3lkNsOyeZmI=,iv:K5pa/4sF9r5fbyKzuVvKnOy5nZDIrDdvqoNJWG9JiOE=,tag:TiNWuGi2SxLHGk7yJuy4FQ==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DNjKf2XoTa3XX+tW3RAuRa24+Q==,iv:QDWCh65Zyp5Uw/yyEg/loutzReBkJ68kjJMxZmw4Pgw=,tag:mTSb+nDHm2nhSRT05kDqFw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV0h6Z0xCYmY5SWFETVE2
        UGNlVWFicnZvM2ZDT3BuKytGa016S0d0NDE4CjNPbGVZK0pZclgzWE9XSllwWHRZ
        ak1LUXJBN2pzcVJTdUtBWlZmbTcxcjAKLS0tIDBjWUhleUIxNW92a3RkR09vQ1Y2
        a3hWREpIMXYrMkRqcjI5bk02WXp1NjAKm01NVqjEH/1Rj8hbJdi5KOG93A03tlYU
        72CXv99K8ZTEZmdFr10pKy0BI1f/Dxhc4n60w3vYPS6KzqCpaS+t0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T02:21:05Z"
  mac: ENC[AES256_GCM,data:F4Pn0unloSSz5sQDjxo8Z1qnbHDAICAmetzKAeGz4d/DqizT6zI35MgGXIhLCZfuTU7tK/eXncCuRR5JDyCjcfLdPUiLE5u1Sx8Fuvu40o9e7m5OhxM/i2XlcX58Y6l/N7BRWja6Y5c70yXASHuy1uhc7JqEirUeSPkdqKpXt0M=,iv:fEDm8YjfuH80RraFUMIT8WnthV5ctXUfl7+0ji4jJSQ=,tag:DyRuBsvfJ00U3rczWbsxIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
