---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snmp-exporter-secret
    template:
      data:
        ups-auths.yml: |
          auths:
            ups_v3:
              version: 3
              security_level: authPriv
              username: "{{ .UPS_SNMP_USERNAME }}"
              password: "{{ .UPS_SNMP_AUTH_PASSWORD }}"
              auth_protocol: SHA
              priv_protocol: AES
              priv_password: "{{ .UPS_SNMP_PRIV_PASSWORD }}"
  dataFrom:
    - extract:
        key: ups-snmp
