# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tautulli-secret
stringData:
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:M60NomI2W0kMt6S1UwDzZMek/HBWBfAGZU5f,iv:IdUdqigatvurqpazQhzMhrHVYaGYHU++opftKwkSLq0=,tag:d/pajL4n3csODcdacBb/lw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNkFQbm8vT3p4cE5PeDZ6
        eWZRYlRwQyszVUhpS1lPc3FzS0s4WExJbmxVCjlPRGh3aVJpY3plYk5wV3VCalBY
        QllLVjdVNWJFYVlwMzhTaEpBR0NJWWsKLS0tIEVkemJURlVobVE0NkNpSzBuSmtT
        eWVkSzllS3NtN0gxdHdGdzVqZXdvM00KpqLQmgWAMZIEGLW7fos8qW5D2zNTJ0zR
        mmp6wPBzIvhgz2WpCfP06W2UWKsEQHmE1u76kPInMfBOKawMeB5jrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T03:56:52Z"
  mac: ENC[AES256_GCM,data:VZ4u3vwLfez+Q0s6vig0G0zBBTYaRSazsRqBnd8GOtZGrN+R7otka5bc8ynuoQ9L/FsIaa/Xz1MHwlwan9GhOkbHJzQFJXTfYcGxH8Fabw/WxRn9Q3NbG0qag9vi1mz0vtCEZoWtUu7Hh2abs4LqP8Apex3YCbgjwEMBDf1510M=,iv:0pihLtjsZro8UZyPVriGDTet0N66HRWia6Virxe1Wao=,tag:Jl7qu98EHJ4L5z9It84VfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
